// const numbers=[10,99,100,17,34];
// console.log(Math.max(...numbers));
// const numbers2=[...numbers,88];
// console.log(numbers2[5]);
const numbers = [45, 12, 36, 84];
numbers.push(25);
console.log(numbers);
function getSum(a, b=9){return a+b;} console.log(getSum(2, 7));
const y = x => x*x;
const x = y(5);
console.log(x);
const  division=  num1, num2 => console.log(num1 /num2);
console.log(division(4,2));